import { INodeTypeDescription, NodeConnectionType } from 'n8n-workflow'

export const pyroTriggerDescription: INodeTypeDescription = {
	displayName: 'Pyrogram Trigger',
	name: 'pyrogramTrigger',
	icon: 'file:pyrogram.svg',
	group: ['trigger'],
	version: 1,
	description: 'Listen for Telegram updates via Pyrogram',
	defaults: {
		name: 'Pyrogram Trigger',
	},
	inputs: [],
	outputs: ['main' as NodeConnectionType],
	credentials: [
		{
			name: 'pyroApi',
			required: true,
		},
	],
	webhooks: [
		{
			name: 'default',
			httpMethod: 'POST',
			responseMode: 'onReceived',
			path: 'pyrogram',
		},
	],
	properties: [
		{
			displayName: 'Update Types',
			name: 'updateTypes',
			type: 'multiOptions',
			options: [
				{ name: 'Message', value: 'message' },
				{ name: 'Edited Message', value: 'edited_message' },
				{ name: 'Channel Post', value: 'channel_post' },
				{ name: 'Edited Channel Post', value: 'edited_channel_post' },
				{ name: 'Inline Query', value: 'inline_query' },
				{ name: 'Callback Query', value: 'callback_query' },
				{ name: 'Chosen Inline Result', value: 'chosen_inline_result' },
				{ name: 'User Status', value: 'user_status' },
				{ name: 'Poll', value: 'poll' },
				{ name: 'Poll Answer', value: 'poll_answer' },
				{ name: 'Chat Member', value: 'chat_member' },
				{ name: 'Chat Join Request', value: 'chat_join_request' },
				{ name: 'Deleted Messages', value: 'deleted_messages' },
				{ name: 'User Typing', value: 'user_typing' },
				{ name: 'Chat Action', value: 'chat_action' },
				{ name: 'Reaction', value: 'reaction' },
				{ name: 'Story', value: 'story' },
			],
			default: ['message'],
			description: 'Select which update types to listen for',
		},
		{
			displayName: 'Filters',
			name: 'filters',
			type: 'collection',
			placeholder: 'Add Filter',
			default: {},
			options: [
				{
					displayName: 'Chat IDs',
					name: 'chatIds',
					type: 'string',
					default: '',
					description: 'Comma-separated list of chat IDs to filter',
				},
				{
					displayName: 'User IDs',
					name: 'userIds',
					type: 'string',
					default: '',
					description: 'Comma-separated list of user IDs to filter',
				},
				{
					displayName: 'Commands',
					name: 'commands',
					type: 'string',
					default: '',
					description:
						'Comma-separated list of commands to filter (e.g., start, help)',
				},
				{
					displayName: 'Text Pattern',
					name: 'textPattern',
					type: 'string',
					default: '',
					description: 'Regex pattern to match message text',
				},
				{
					displayName: 'Media Types',
					name: 'mediaTypes',
					type: 'multiOptions',
					options: [
						{ name: 'Photo', value: 'photo' },
						{ name: 'Video', value: 'video' },
						{ name: 'Audio', value: 'audio' },
						{ name: 'Document', value: 'document' },
						{ name: 'Sticker', value: 'sticker' },
						{ name: 'Animation', value: 'animation' },
						{ name: 'Voice', value: 'voice' },
						{ name: 'Video Note', value: 'video_note' },
					],
					default: [],
				},
			],
		},
	],
}
