import { INodeTypeDescription } from 'n8n-workflow'

export const triggerDescription: INodeTypeDescription = {
	displayName: 'Pyrogram Trigger',
	name: 'pyrogramTrigger',
	icon: 'file:pyro.svg',
	group: ['trigger'],
	version: 1,
	description: 'Trigger workflows from Telegram events using Pyrogram',
	defaults: { name: 'Pyrogram Trigger' },
	inputs: [],
	outputs: ['main'],
	credentials: [{ name: 'pyroApi', required: true }],
	webhooks: [
		{
			name: 'default',
			httpMethod: 'POST',
			responseMode: 'onReceived',
			path: 'pyrogram-webhook',
		},
	],
	properties: [
		{
			displayName: 'Trigger Type',
			name: 'triggerType',
			type: 'options',
			options: [
				{ name: 'Message Handler', value: 'message' },
				{ name: 'Update Handler', value: 'update' },
				{ name: 'Polling', value: 'polling' },
			],
			default: 'message',
		},
		{
			displayName: 'Message Filters',
			name: 'messageFilters',
			type: 'collection',
			placeholder: 'Add Filter',
			default: {},
			options: [
				{
					name: 'chatType',
					displayName: 'Chat Type',
					type: 'multiOptions',
					options: [
						{ name: 'Private', value: 'private' },
						{ name: 'Group', value: 'group' },
						{ name: 'Channel', value: 'channel' },
						{ name: 'Bot', value: 'bot' },
					],
				},
				{ name: 'chatId', displayName: 'Chat ID', type: 'string', default: '' },
				{
					name: 'userIds',
					displayName: 'User IDs',
					type: 'string',
					default: '',
				},
				{
					name: 'textPattern',
					displayName: 'Text Pattern (Regex)',
					type: 'string',
					default: '',
				},
				{
					name: 'commands',
					displayName: 'Commands',
					type: 'string',
					default: '',
				},
			],
			displayOptions: { show: { triggerType: ['message'] } },
		},
		{
			displayName: 'Update Handlers',
			name: 'updateHandlers',
			type: 'multiOptions',
			options: [
				{ name: 'Chat Member Updated', value: 'on_chat_member_updated' },
				{ name: 'Callback Query', value: 'on_callback_query' },
				{ name: 'Inline Query', value: 'on_inline_query' },
				{ name: 'Chosen Inline Result', value: 'on_chosen_inline_result' },
				{ name: 'User Status', value: 'on_user_status' },
				{ name: 'Poll', value: 'on_poll' },
				{ name: 'Poll Answer', value: 'on_poll_answer' },
				{ name: 'Chat Join Request', value: 'on_chat_join_request' },
			],
			default: ['on_callback_query'],
			displayOptions: { show: { triggerType: ['update'] } },
		},
		{
			displayName: 'Polling Method',
			name: 'pollingMethod',
			type: 'options',
			options: [
				{ name: 'Chat History', value: 'get_chat_history' },
				{ name: 'Dialogs', value: 'get_dialogs' },
				{ name: 'Chat Members', value: 'get_chat_members' },
				{ name: 'Chat Members Count', value: 'get_chat_members_count' },
				{ name: 'Search Messages', value: 'search_messages' },
			],
			default: 'get_chat_history',
			displayOptions: { show: { triggerType: ['polling'] } },
		},
		{
			displayName: 'Polling Interval (seconds)',
			name: 'pollingInterval',
			type: 'number',
			default: 60,
			description: 'Minimum 10 seconds',
			displayOptions: { show: { triggerType: ['polling'] } },
		},
		{
			displayName: 'Polling Config',
			name: 'pollingConfig',
			type: 'collection',
			default: {},
			options: [
				{ name: 'chatId', displayName: 'Chat ID', type: 'string', default: '' },
				{ name: 'limit', displayName: 'Limit', type: 'number', default: 100 },
				{
					name: 'searchQuery',
					displayName: 'Search Query',
					type: 'string',
					default: '',
				},
				{
					name: 'onlyNew',
					displayName: 'Only New Items',
					type: 'boolean',
					default: true,
				},
			],
			displayOptions: { show: { triggerType: ['polling'] } },
		},
	],
}
